import { pgTable, uuid, text, timestamp, boolean, numeric } from 'drizzle-orm/pg-core';
import { user } from './auth-schema.js';

export const userProfiles = pgTable('user_profiles', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id').notNull().unique().references(() => user.id, { onDelete: 'cascade' }),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  dateOfBirth: text('date_of_birth').notNull(),
  placeOfBirthCity: text('place_of_birth_city'),
  placeOfBirthProvince: text('place_of_birth_province'),
  placeOfBirthCountry: text('place_of_birth_country'),
  addressHouse: text('address_house'),
  addressStreet: text('address_street'),
  addressSuburb: text('address_suburb'),
  addressCity: text('address_city'),
  addressProvince: text('address_province'),
  addressCountry: text('address_country'),
  phonePrimary: text('phone_primary').notNull(),
  phoneSecondary: text('phone_secondary'),
  email: text('email').notNull(),
  idNumber: text('id_number'),
  languagePreference: text('language_preference').default('en').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const applications = pgTable('applications', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  applicationType: text('application_type').notNull(),
  applicationSubtype: text('application_subtype').notNull(),
  isMinor: boolean('is_minor').default(false).notNull(),
  status: text('status').default('draft').notNull(),
  referenceNumber: text('reference_number').unique().notNull(),
  feeAmount: numeric('fee_amount').notNull(),
  feePaid: boolean('fee_paid').default(false).notNull(),
  paymentMethod: text('payment_method'),
  paymentReference: text('payment_reference'),
  paymentDate: timestamp('payment_date', { withTimezone: true }),
  submittedAt: timestamp('submitted_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const applicationDetails = pgTable('application_details', {
  id: uuid('id').primaryKey().defaultRandom(),
  applicationId: uuid('application_id').notNull().unique().references(() => applications.id, { onDelete: 'cascade' }),
  firstName: text('first_name'),
  lastName: text('last_name'),
  dateOfBirth: text('date_of_birth'),
  placeOfBirthCity: text('place_of_birth_city'),
  placeOfBirthProvince: text('place_of_birth_province'),
  placeOfBirthCountry: text('place_of_birth_country'),
  addressHouse: text('address_house'),
  addressStreet: text('address_street'),
  addressSuburb: text('address_suburb'),
  addressCity: text('address_city'),
  addressProvince: text('address_province'),
  addressCountry: text('address_country'),
  phonePrimary: text('phone_primary'),
  phoneSecondary: text('phone_secondary'),
  email: text('email'),
  idNumber: text('id_number'),
  guardianName: text('guardian_name'),
  guardianSurname: text('guardian_surname'),
  guardianIdNumber: text('guardian_id_number'),
  birthCertificateNumber: text('birth_certificate_number'),
  birthCertificateUrl: text('birth_certificate_url'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const statusUpdates = pgTable('status_updates', {
  id: uuid('id').primaryKey().defaultRandom(),
  applicationId: uuid('application_id').notNull().references(() => applications.id, { onDelete: 'cascade' }),
  status: text('status').notNull(),
  message: text('message').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});
