import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'af' | 'zu' | 'xh';

const STORAGE_KEY = 'identifEYE_language';

const translations: Record<Language, Record<string, string>> = {
  en: {
    welcome: 'Welcome to IDentifEYE',
    tagline: 'Your Digital Identity Hub',
    sign_in: 'Sign In',
    sign_up: 'Sign Up',
    continue_with_google: 'Continue with Google',
    continue_with_apple: 'Continue with Apple',
    email: 'Email',
    password: 'Password',
    name: 'Full Name',
    or: 'or',
    language_select: 'Language',
    select_language: 'Select Language',
    home: 'Home',
    applications: 'Applications',
    status: 'Status',
    profile: 'Profile',
    settings: 'Settings',
    apply_for_id: 'Apply for ID',
    apply_for_passport: 'Apply for Passport',
    new_application: 'New Application',
    renewal: 'Renewal',
    application_type: 'Application Type',
    document_type: 'Document Type',
    id_document: 'ID Document',
    passport: 'Passport',
    new_id_free: 'New ID — FREE',
    id_renewal_fee: 'ID Renewal — R140',
    passport_fee: 'Passport — R600',
    personal_details: 'Personal Details',
    address_details: 'Address Details',
    contact_details: 'Contact Details',
    guardian_details: 'Guardian Details',
    first_name: 'First Name',
    last_name: 'Last Name',
    date_of_birth: 'Date of Birth',
    place_of_birth: 'Place of Birth',
    current_address: 'Current Address',
    phone_number: 'Phone Number',
    email_address: 'Email Address',
    id_number: 'ID Number',
    guardian_name: 'Guardian First Name',
    guardian_surname: 'Guardian Surname',
    guardian_id_number: 'Guardian ID Number',
    birth_certificate_number: 'Birth Certificate Number',
    upload_birth_certificate: 'Upload Birth Certificate',
    minor_application: 'Minor Application',
    payment: 'Payment',
    select_bank: 'Select Your Bank',
    pay_now: 'Pay Now',
    payment_success: 'Payment Successful',
    payment_failed: 'Payment Failed',
    absa: 'ABSA',
    capitec: 'Capitec',
    standard_bank: 'Standard Bank',
    fnb: 'FNB',
    discovery: 'Discovery Bank',
    submit_application: 'Submit Application',
    application_submitted: 'Application Submitted!',
    track_status: 'Track Status',
    status_draft: 'Draft',
    status_submitted: 'Submitted',
    status_processing: 'Processing',
    status_approved: 'Approved',
    status_rejected: 'Rejected',
    status_ready: 'Ready for Collection',
    reference_number: 'Reference Number',
    submitted_on: 'Submitted On',
    fee: 'Fee',
    paid: 'Paid',
    unpaid: 'Unpaid',
    save: 'Save',
    cancel: 'Cancel',
    next: 'Next',
    back: 'Back',
    done: 'Done',
    loading: 'Loading...',
    error_occurred: 'An error occurred',
    try_again: 'Try Again',
    popi_consent: 'I consent to the processing of my personal information in accordance with POPI Act',
    popi_title: 'POPI Act Consent',
    popi_body: 'By proceeding, you consent to the collection and processing of your personal information as required by the Protection of Personal Information Act (POPIA) for the purpose of processing your identity document application.',
    biometric_title: 'Biometric Authentication',
    biometric_subtitle: 'Use your fingerprint or face to sign in securely',
    use_fingerprint: 'Use Biometrics',
    use_face_id: 'Use Face ID',
    no_applications: 'No Applications Yet',
    start_application: 'Start Your First Application',
    my_applications: 'My Applications',
    profile_complete: 'Profile Complete',
    profile_incomplete: 'Profile Incomplete',
    edit_profile: 'Edit Profile',
    save_profile: 'Save Profile',
    greeting: 'Hello',
    track_my_application: 'Track My Application',
    go_home: 'Go Home',
    processing_time: 'Estimated processing time: 10–15 working days',
    review_submit: 'Review & Submit',
    proceed_to_payment: 'Proceed to Payment',
    is_minor: 'Is this for a minor (under 16)?',
    yes: 'Yes',
    no: 'No',
    popi_compliance: 'Your data is protected under the POPI Act',
    sign_out: 'Sign Out',
    security: 'Security',
    biometric_login: 'Biometric Login',
    language_preference: 'Language Preference',
    address: 'Address',
    contact: 'Contact',
    all: 'All',
    pending: 'Pending',
    completed: 'Completed',
    search_reference: 'Search by reference number...',
    status_timeline: 'Status Timeline',
    new_app: 'New',
    filter: 'Filter',
    application_detail: 'Application Detail',
    city: 'City',
    province: 'Province',
    country: 'Country',
    house_number: 'House / Unit Number',
    street: 'Street Name',
    suburb: 'Suburb',
    phone_secondary: 'Secondary Phone (optional)',
    processing_payment: 'Processing payment...',
    secure_payment: 'Payments are secured and encrypted',
    sawubona: 'Hello',
    quick_actions: 'Quick Actions',
    recent_applications: 'Recent Applications',
    digital_identity_hub: 'Your Digital Identity Hub',
    south_africa: 'South Africa',
    view_all: 'View All',
    // Home Affairs verification
    ha_verify_title: 'Identity Verification',
    ha_verify_subtitle: 'Before registering, we need to verify your identity against the Home Affairs database to prevent fraud.',
    ha_what_you_need: 'What you need:',
    ha_need_id: 'Your 13-digit South African ID number',
    ha_need_name: 'Your first name (as it appears on your ID)',
    ha_need_surname: 'Your surname (as it appears on your ID)',
    ha_need_face: 'A selfie for facial recognition',
    ha_demo_hint: 'Demo: ID 0000000000000 · Name "Demo" · Surname "User" · any selfie.',
    ha_start_verification: 'Start Verification',
    ha_enter_details: 'Enter Your Details',
    ha_enter_details_sub: 'Enter your SA ID number, first name and surname exactly as they appear on your ID document.',
    ha_face_capture: 'Face Verification',
    ha_face_capture_sub: 'Take a selfie or upload a photo. This will be matched against Home Affairs biometric records.',
    ha_tap_to_capture: 'Tap to take a selfie',
    ha_use_camera: 'Take Selfie',
    ha_from_gallery: 'From Gallery',
    ha_verify_now: 'Verify Identity',
    ha_skip_photo: 'Verify Without Photo',
    ha_verifying: 'Verifying Identity...',
    ha_verifying_sub: 'Cross-referencing with Home Affairs database. This may take a moment.',
    ha_verified: 'Identity Verified',
    ha_welcome: 'Welcome,',
    ha_verified_sub: 'Your identity has been confirmed. You can now complete your registration.',
    ha_continue_register: 'Continue to Register',
    ha_not_verified: 'Verification Failed',
    ha_verify_identity: 'Verify Identity with Home Affairs',
    ha_verify_required: 'Required before registration',
    ha_identity_verified: 'Identity Verified ✓',
    // Notifications
    notif_submitted: 'Application submitted successfully',
    notif_processing: 'Your application is being processed',
    notif_approved: 'Your application has been approved',
    notif_ready: 'Your document is ready for collection',
    notif_payment_success: 'Payment successful',
    // Upload
    upload_photo: 'Upload Photo',
    capture_photo: 'Take Photo',
    photo_uploaded: 'Photo uploaded',
    // Minor biometrics
    minor_biometrics: 'Minor Biometric Capture',
    minor_biometrics_sub: 'Capture the minor\'s fingerprint and face photo for biometric registration.',
    capture_minor_face: 'Capture Minor\'s Face Photo',
    minor_face_captured: 'Face photo captured',
    // Status
    status: 'Status',
  },
  af: {
    welcome: 'Welkom by IDentifEYE',
    tagline: 'Jou Digitale Identiteitsentrum',
    sign_in: 'Teken In',
    sign_up: 'Registreer',
    continue_with_google: 'Gaan voort met Google',
    continue_with_apple: 'Gaan voort met Apple',
    email: 'E-pos',
    password: 'Wagwoord',
    name: 'Volle Naam',
    or: 'of',
    language_select: 'Taal',
    select_language: 'Kies Taal',
    home: 'Tuis',
    applications: 'Aansoeke',
    status: 'Status',
    profile: 'Profiel',
    settings: 'Instellings',
    apply_for_id: 'Aansoek vir ID',
    apply_for_passport: 'Aansoek vir Paspoort',
    new_application: 'Nuwe Aansoek',
    renewal: 'Hernuwing',
    application_type: 'Aansoektipe',
    document_type: 'Dokumenttipe',
    id_document: 'ID-dokument',
    passport: 'Paspoort',
    new_id_free: 'Nuwe ID — GRATIS',
    id_renewal_fee: 'ID Hernuwing — R140',
    passport_fee: 'Paspoort — R600',
    personal_details: 'Persoonlike Besonderhede',
    address_details: 'Adresbesonderhede',
    contact_details: 'Kontakbesonderhede',
    guardian_details: 'Voogbesonderhede',
    first_name: 'Voornaam',
    last_name: 'Van',
    date_of_birth: 'Geboortedatum',
    place_of_birth: 'Geboorteplek',
    current_address: 'Huidige Adres',
    phone_number: 'Telefoonnommer',
    email_address: 'E-posadres',
    id_number: 'ID-nommer',
    guardian_name: 'Voog Voornaam',
    guardian_surname: 'Voog Van',
    guardian_id_number: 'Voog ID-nommer',
    birth_certificate_number: 'Geboortesertifikatnommer',
    upload_birth_certificate: 'Laai Geboortesertifikaat op',
    minor_application: 'Minderjarige Aansoek',
    payment: 'Betaling',
    select_bank: 'Kies Jou Bank',
    pay_now: 'Betaal Nou',
    payment_success: 'Betaling Suksesvol',
    payment_failed: 'Betaling Misluk',
    absa: 'ABSA',
    capitec: 'Capitec',
    standard_bank: 'Standard Bank',
    fnb: 'FNB',
    discovery: 'Discovery Bank',
    submit_application: 'Dien Aansoek In',
    application_submitted: 'Aansoek Ingedien!',
    track_status: 'Volg Status',
    status_draft: 'Konsep',
    status_submitted: 'Ingedien',
    status_processing: 'Verwerking',
    status_approved: 'Goedgekeur',
    status_rejected: 'Afgekeur',
    status_ready: 'Gereed vir Insameling',
    reference_number: 'Verwysingsnommer',
    submitted_on: 'Ingedien Op',
    fee: 'Fooi',
    paid: 'Betaal',
    unpaid: 'Onbetaald',
    save: 'Stoor',
    cancel: 'Kanselleer',
    next: 'Volgende',
    back: 'Terug',
    done: 'Klaar',
    loading: 'Laai...',
    error_occurred: 'n Fout het voorgekom',
    try_again: 'Probeer Weer',
    popi_consent: 'Ek stem in tot die verwerking van my persoonlike inligting ingevolge die POPI-wet',
    popi_title: 'POPI-wet Toestemming',
    popi_body: 'Deur voort te gaan, stem u in tot die insameling en verwerking van u persoonlike inligting soos vereis deur die Wet op Beskerming van Persoonlike Inligting (POPIA).',
    biometric_title: 'Biometriese Verifikasie',
    biometric_subtitle: 'Gebruik jou vingerafdruk of gesig om veilig aan te meld',
    use_fingerprint: 'Gebruik Biometrie',
    use_face_id: 'Gebruik Gesig-ID',
    no_applications: 'Geen Aansoeke Nog',
    start_application: 'Begin Jou Eerste Aansoek',
    my_applications: 'My Aansoeke',
    profile_complete: 'Profiel Volledig',
    profile_incomplete: 'Profiel Onvolledig',
    edit_profile: 'Wysig Profiel',
    save_profile: 'Stoor Profiel',
    greeting: 'Hallo',
    track_my_application: 'Volg My Aansoek',
    go_home: 'Gaan Tuis',
    processing_time: 'Geskatte verwerkingstyd: 10–15 werksdae',
    review_submit: 'Hersien & Indien',
    proceed_to_payment: 'Gaan na Betaling',
    is_minor: 'Is dit vir n minderjarige (onder 16)?',
    yes: 'Ja',
    no: 'Nee',
    popi_compliance: 'Jou data word beskerm ingevolge die POPI-wet',
    sign_out: 'Teken Uit',
    security: 'Sekuriteit',
    biometric_login: 'Biometriese Aanmelding',
    language_preference: 'Taalvoorkeur',
    address: 'Adres',
    contact: 'Kontak',
    all: 'Alles',
    pending: 'Hangende',
    completed: 'Voltooid',
    search_reference: 'Soek op verwysingsnommer...',
    status_timeline: 'Statustydlyn',
    new_app: 'Nuut',
    filter: 'Filter',
    application_detail: 'Aansoekbesonderhede',
    city: 'Stad',
    province: 'Provinsie',
    country: 'Land',
    house_number: 'Huis / Eenheidnommer',
    street: 'Straatnaam',
    suburb: 'Voorstad',
    phone_secondary: 'Sekondêre Telefoon (opsioneel)',
    processing_payment: 'Betaling verwerk...',
    secure_payment: 'Betalings is beveilig en geënkripteer',
    sawubona: 'Hallo',
    quick_actions: 'Vinnige Aksies',
    recent_applications: 'Onlangse Aansoeke',
    digital_identity_hub: 'Jou Digitale Identiteitsentrum',
    south_africa: 'Suid-Afrika',
    view_all: 'Sien Alles',
    ha_verify_title: 'Identiteitsverifikasie',
    ha_verify_subtitle: 'Voor registrasie moet ons jou identiteit teen die Binnelandse Sake-databasis verifieer.',
    ha_what_you_need: 'Wat jy nodig het:',
    ha_need_id: 'Jou 13-syfer Suid-Afrikaanse ID-nommer',
    ha_need_name: 'Jou voornaam (soos op jou ID)',
    ha_need_surname: 'Jou van (soos op jou ID)',
    ha_need_face: "'n Selfie vir gesigherkenning",
    ha_demo_hint: 'Demo: ID 0000000000000 · Naam "Demo" · Van "User" · enige selfie.',
    ha_start_verification: 'Begin Verifikasie',
    ha_enter_details: 'Voer Jou Besonderhede In',
    ha_enter_details_sub: 'Voer jou SA ID-nommer, voornaam en van in soos dit op jou ID-dokument verskyn.',
    ha_face_capture: 'Gesigverifikasie',
    ha_face_capture_sub: 'Neem \'n selfie of laai \'n foto op.',
    ha_tap_to_capture: 'Tik om \'n selfie te neem',
    ha_use_camera: 'Neem Selfie',
    ha_from_gallery: 'Van Galery',
    ha_verify_now: 'Verifieer Identiteit',
    ha_skip_photo: 'Verifieer Sonder Foto',
    ha_verifying: 'Identiteit word geverifieer...',
    ha_verifying_sub: 'Kruisverwysing met Binnelandse Sake-databasis.',
    ha_verified: 'Identiteit Geverifieer',
    ha_welcome: 'Welkom,',
    ha_verified_sub: 'Jou identiteit is bevestig. Jy kan nou jou registrasie voltooi.',
    ha_continue_register: 'Gaan voort na Registrasie',
    ha_not_verified: 'Verifikasie Misluk',
    ha_verify_identity: 'Verifieer Identiteit met Binnelandse Sake',
    ha_verify_required: 'Vereis voor registrasie',
    ha_identity_verified: 'Identiteit Geverifieer ✓',
    notif_submitted: 'Aansoek suksesvol ingedien',
    notif_processing: 'Jou aansoek word verwerk',
    notif_approved: 'Jou aansoek is goedgekeur',
    notif_ready: 'Jou dokument is gereed vir insameling',
    notif_payment_success: 'Betaling suksesvol',
    upload_photo: 'Laai Foto Op',
    capture_photo: 'Neem Foto',
    photo_uploaded: 'Foto opgelaai',
    minor_biometrics: 'Biometriese Vaslegging van Minderjarige',
    minor_biometrics_sub: 'Neem die minderjarige se vingerafdruk en gesigfoto vir biometriese registrasie.',
    capture_minor_face: 'Neem Gesigfoto van Minderjarige',
    minor_face_captured: 'Gesigfoto vasgelê',
    status: 'Status',
  },
  zu: {
    welcome: 'Wamukelekile ku-IDentifEYE',
    tagline: 'Isikhungo Sakho Sobunikazi Bedijithali',
    sign_in: 'Ngena',
    sign_up: 'Bhalisa',
    continue_with_google: 'Qhubeka nge-Google',
    continue_with_apple: 'Qhubeka ne-Apple',
    email: 'I-imeyili',
    password: 'Iphasiwedi',
    name: 'Igama Eligcwele',
    or: 'noma',
    language_select: 'Ulimi',
    select_language: 'Khetha Ulimi',
    home: 'Ikhaya',
    applications: 'Izicelo',
    status: 'Isimo',
    profile: 'Iphrofayili',
    settings: 'Izilungiselelo',
    apply_for_id: 'Faka Isicelo se-ID',
    apply_for_passport: 'Faka Isicelo sePassipoti',
    new_application: 'Isicelo Esisha',
    renewal: 'Ukuvuselela',
    application_type: 'Uhlobo Lwesicelo',
    document_type: 'Uhlobo Lwedokhumenti',
    id_document: 'Idokhumenti le-ID',
    passport: 'Ipassipoti',
    new_id_free: 'I-ID Entsha — MAHHALA',
    id_renewal_fee: 'Ukuvuselela i-ID — R140',
    passport_fee: 'Ipassipoti — R600',
    personal_details: 'Imininingwane Yomuntu',
    address_details: 'Imininingwane Yekheli',
    contact_details: 'Imininingwane Yokuxhumana',
    guardian_details: 'Imininingwane Yomgcini',
    first_name: 'Igama Lokuqala',
    last_name: 'Isibongo',
    date_of_birth: 'Usuku Lokuzalwa',
    place_of_birth: 'Indawo Yokuzalwa',
    current_address: 'Ikheli Langamanje',
    phone_number: 'Inombolo Yocingo',
    email_address: 'Ikheli le-imeyili',
    id_number: 'Inombolo ye-ID',
    guardian_name: 'Igama Lomgcini',
    guardian_surname: 'Isibongo Somgcini',
    guardian_id_number: 'Inombolo ye-ID Yomgcini',
    birth_certificate_number: 'Inombolo Yesitifiketi Sokuzalwa',
    upload_birth_certificate: 'Layisha Isitifiketi Sokuzalwa',
    minor_application: 'Isicelo Somuntu Omncane',
    payment: 'Inkokhelo',
    select_bank: 'Khetha Ibhange Lakho',
    pay_now: 'Khokha Manje',
    payment_success: 'Inkokhelo Iphumelele',
    payment_failed: 'Inkokhelo Yehlulekile',
    absa: 'ABSA',
    capitec: 'Capitec',
    standard_bank: 'Standard Bank',
    fnb: 'FNB',
    discovery: 'Discovery Bank',
    submit_application: 'Thumela Isicelo',
    application_submitted: 'Isicelo Sithunyiwe!',
    track_status: 'Landelela Isimo',
    status_draft: 'Idrafti',
    status_submitted: 'Ithunyelwe',
    status_processing: 'Iyacutshungulwa',
    status_approved: 'Imukelwe',
    status_rejected: 'Ikhishiwe',
    status_ready: 'Ilungele Ukuqoqwa',
    reference_number: 'Inombolo Yesethulo',
    submitted_on: 'Ithunyelwe Ngo',
    fee: 'Imali',
    paid: 'Ikhokhiwe',
    unpaid: 'Ayikhokhiwe',
    save: 'Gcina',
    cancel: 'Khansela',
    next: 'Okulandelayo',
    back: 'Emuva',
    done: 'Kuqedile',
    loading: 'Iyalayisha...',
    error_occurred: 'Kukhona iphutha',
    try_again: 'Zama Futhi',
    popi_consent: 'Ngiyavuma ukucutshungulwa kwemininingwane yami ngokwemithetho ye-POPI',
    popi_title: 'Imvume ye-POPI Act',
    popi_body: 'Ngokuqhubeka, uvuma ukuqoqwa nokucutshungulwa kwemininingwane yakho yomuntu siqu njengoba kudingelwa uMthetho Wokuqinisekiswa Kwemininingwane Yomuntu Siqu (POPIA).',
    biometric_title: 'Ukuqinisekiswa Kwezimpawu Zomzimba',
    biometric_subtitle: 'Sebenzisa izigxivizo zeminwe noma ubuso bakho ukungena ngokuphepha',
    use_fingerprint: 'Sebenzisa Izimpawu Zomzimba',
    use_face_id: 'Sebenzisa Ubuso',
    no_applications: 'Azikho Izicelo Okwamanje',
    start_application: 'Qala Isicelo Sakho Sokuqala',
    my_applications: 'Izicelo Zami',
    profile_complete: 'Iphrofayili Igcwele',
    profile_incomplete: 'Iphrofayili Ayigcwele',
    edit_profile: 'Hlela Iphrofayili',
    save_profile: 'Gcina Iphrofayili',
    greeting: 'Sawubona',
    track_my_application: 'Landelela Isicelo Sami',
    go_home: 'Buyela Ekhaya',
    processing_time: 'Isikhathi sokucutshungulwa: Izinsuku eziyi-10–15 zomsebenzi',
    review_submit: 'Hlola & Thumela',
    proceed_to_payment: 'Qhubeka Ngenkokhelo',
    is_minor: 'Ingabe lokhu kungowomuntu omncane (ngaphansi kwe-16)?',
    yes: 'Yebo',
    no: 'Cha',
    popi_compliance: 'Idatha yakho ivikelwe ngaphansi kwe-POPI Act',
    sign_out: 'Phuma',
    security: 'Ukuphepha',
    biometric_login: 'Ukungena Ngezimpawu Zomzimba',
    language_preference: 'Okuthandwayo Kolimi',
    address: 'Ikheli',
    contact: 'Xhumana',
    all: 'Konke',
    pending: 'Kulindile',
    completed: 'Kuqediwe',
    search_reference: 'Sesha ngenombolo yesethulo...',
    status_timeline: 'Uhlelo Lwesikhathi Sesimo',
    new_app: 'Okusha',
    filter: 'Hlunga',
    application_detail: 'Imininingwane Yesicelo',
    city: 'Idolobha',
    province: 'Isifundazwe',
    country: 'Izwe',
    house_number: 'Inombolo Yendlu / Iyunithi',
    street: 'Igama Lomgwaqo',
    suburb: 'Indawo',
    phone_secondary: 'Ucingo Lwesibili (okukhethekile)',
    processing_payment: 'Icubungula inkokhelo...',
    secure_payment: 'Izinkokhelo zivikelwe futhi zikhipha imfihlo',
    sawubona: 'Sawubona',
    quick_actions: 'Izenzo Ezisheshayo',
    recent_applications: 'Izicelo Zamuva',
    digital_identity_hub: 'Isikhungo Sakho Sobunikazi Bedijithali',
    south_africa: 'iNingizimu Afrika',
    view_all: 'Bona Konke',
    ha_verify_title: 'Ukuqinisekiswa Kobunikazi',
    ha_verify_subtitle: 'Ngaphambi kokubhalisa, sidinga ukuqinisekisa ubunikazi bakho ngokusebenzisa idatha ye-Home Affairs.',
    ha_what_you_need: 'Okudingekayo:',
    ha_need_id: 'Inombolo yakho ye-ID yaseNingizimu Afrika enezinombolo eziyi-13',
    ha_need_name: 'Igama lakho lokuqala (njengoba likulo i-ID yakho)',
    ha_need_surname: 'Isibongo sakho (njengoba sikulo i-ID yakho)',
    ha_need_face: 'Isithombe sakho sobuso sokubona ubuso',
    ha_demo_hint: 'Demo: I-ID 0000000000000 · Igama "Demo" · Isibongo "User" · noma isiphi isithombe.',
    ha_start_verification: 'Qala Ukuqinisekisa',
    ha_enter_details: 'Faka Imininingwane Yakho',
    ha_enter_details_sub: 'Faka inombolo yakho ye-SA ID, igama lokuqala kanye nesibongo njengoba kubonakala empepha-mvume yakho ye-ID.',
    ha_face_capture: 'Ukuqinisekiswa Kobuso',
    ha_face_capture_sub: 'Thatha isithombe sakho noma layisha isithombe.',
    ha_tap_to_capture: 'Thepha ukuthatha isithombe',
    ha_use_camera: 'Thatha Isithombe',
    ha_from_gallery: 'Evela Egalerini',
    ha_verify_now: 'Qinisekisa Ubunikazi',
    ha_skip_photo: 'Qinisekisa Ngaphandle Kwesithombe',
    ha_verifying: 'Iyaqinisekisa Ubunikazi...',
    ha_verifying_sub: 'Iyaxhumana nedatha ye-Home Affairs.',
    ha_verified: 'Ubunikazi Buqinisekisiwe',
    ha_welcome: 'Wamukelekile,',
    ha_verified_sub: 'Ubunikazi bakho buqinisekisiwe. Manje ungaqedela ukubhalisa kwakho.',
    ha_continue_register: 'Qhubeka Ukubhalisa',
    ha_not_verified: 'Ukuqinisekisa Kwehlulekile',
    ha_verify_identity: 'Qinisekisa Ubunikazi ne-Home Affairs',
    ha_verify_required: 'Kudingeka ngaphambi kokubhalisa',
    ha_identity_verified: 'Ubunikazi Buqinisekisiwe ✓',
    notif_submitted: 'Isicelo sithunyiwe ngempumelelo',
    notif_processing: 'Isicelo sakho siyacutshungulwa',
    notif_approved: 'Isicelo sakho samukelwe',
    notif_ready: 'Idokhumenti yakho ilungele ukuqoqwa',
    notif_payment_success: 'Inkokhelo iphumelele',
    upload_photo: 'Layisha Isithombe',
    capture_photo: 'Thatha Isithombe',
    photo_uploaded: 'Isithombe silayishiwe',
    minor_biometrics: 'Ukuthwebula Izimpawu Zomzimba Zomuntu Omncane',
    minor_biometrics_sub: 'Thwebula izigxivizo zeminwe kanye nesithombe sobuso somuntu omncane.',
    capture_minor_face: 'Thwebula Isithombe Sobuso Somuntu Omncane',
    minor_face_captured: 'Isithombe sobuso sithwebulwe',
    status: 'Isimo',
  },
  xh: {
    welcome: 'Wamkelekile ku-IDentifEYE',
    tagline: 'Iziko Lakho Lobuqu Bedijithali',
    sign_in: 'Ngena',
    sign_up: 'Bhalisa',
    continue_with_google: 'Qhubeka nge-Google',
    continue_with_apple: 'Qhubeka ne-Apple',
    email: 'I-imeyile',
    password: 'Ipasiwedi',
    name: 'Igama Eligcweleyo',
    or: 'okanye',
    language_select: 'Ulwimi',
    select_language: 'Khetha Ulwimi',
    home: 'Ekhaya',
    applications: 'Izicelo',
    status: 'Imeko',
    profile: 'Iprofayile',
    settings: 'Izisetingi',
    apply_for_id: 'Faka Isicelo se-ID',
    apply_for_passport: 'Faka Isicelo sePassipoti',
    new_application: 'Isicelo Esitsha',
    renewal: 'Ukuhlaziya',
    application_type: 'Uhlobo Lwesicelo',
    document_type: 'Uhlobo Lwempepha',
    id_document: 'Impepha ye-ID',
    passport: 'Ipassipoti',
    new_id_free: 'I-ID Entsha — SIMAHLA',
    id_renewal_fee: 'Ukuhlaziya i-ID — R140',
    passport_fee: 'Ipassipoti — R600',
    personal_details: 'Iinkcukacha Zobuqu',
    address_details: 'Iinkcukacha Zedilesi',
    contact_details: 'Iinkcukacha Zoqhagamshelwano',
    guardian_details: 'Iinkcukacha Zomgcini',
    first_name: 'Igama Lokuqala',
    last_name: 'Ifani',
    date_of_birth: 'Umhla Wokuzalwa',
    place_of_birth: 'Indawo Yokuzalwa',
    current_address: 'Idilesi Yangoku',
    phone_number: 'Inombolo Yefoni',
    email_address: 'Idilesi ye-imeyile',
    id_number: 'Inombolo ye-ID',
    guardian_name: 'Igama Lomgcini',
    guardian_surname: 'Ifani Lomgcini',
    guardian_id_number: 'Inombolo ye-ID Yomgcini',
    birth_certificate_number: 'Inombolo Yesatifikethi Sokuzalwa',
    upload_birth_certificate: 'Layisha Isatifikethi Sokuzalwa',
    minor_application: 'Isicelo Somntu Omncinci',
    payment: 'Intlawulo',
    select_bank: 'Khetha Ibhanki Yakho',
    pay_now: 'Hlawula Ngoku',
    payment_success: 'Intlawulo Iphumelele',
    payment_failed: 'Intlawulo Yehlulekile',
    absa: 'ABSA',
    capitec: 'Capitec',
    standard_bank: 'Standard Bank',
    fnb: 'FNB',
    discovery: 'Discovery Bank',
    submit_application: 'Thumela Isicelo',
    application_submitted: 'Isicelo Sithunyiwe!',
    track_status: 'Landelela Imeko',
    status_draft: 'Idrafti',
    status_submitted: 'Ithunyelwe',
    status_processing: 'Iyacutshungulwa',
    status_approved: 'Yamkelwe',
    status_rejected: 'Yaliwe',
    status_ready: 'Ilungele Ukuqokelelwa',
    reference_number: 'Inombolo Yesalathiso',
    submitted_on: 'Ithunyelwe Ngo',
    fee: 'Imali',
    paid: 'Ihlawuliwe',
    unpaid: 'Ayihlawulwanga',
    save: 'Gcina',
    cancel: 'Rhoxisa',
    next: 'Okulandelayo',
    back: 'Emva',
    done: 'Kwenziwe',
    loading: 'Iyalayisha...',
    error_occurred: 'Kukho impazamo',
    try_again: 'Zama Kwakhona',
    popi_consent: 'Ndiyavuma ukucutshungulwa kwemininingwane yam ngokwemithetho ye-POPI',
    popi_title: 'Imvume ye-POPI Act',
    popi_body: 'Ngokuqhubeka, uyavuma ukuqokelelwa nokucutshungulwa kwemininingwane yakho yobuqu njengoko kufunwa nguMthetho Wokukhuselwa Kwemininingwane Yobuqu (POPIA).',
    biometric_title: 'Ukuqinisekiswa Kwezimpawu Zomzimba',
    biometric_subtitle: 'Sebenzisa izigxivizo zeminwe okanye ubuso bakho ukungena ngokukhuselekileyo',
    use_fingerprint: 'Sebenzisa Izimpawu Zomzimba',
    use_face_id: 'Sebenzisa Ubuso',
    no_applications: 'Azikho Izicelo Okwangoku',
    start_application: 'Qala Isicelo Sakho Sokuqala',
    my_applications: 'Izicelo Zam',
    profile_complete: 'Iprofayile Igcweleyo',
    profile_incomplete: 'Iprofayile Ayigcwelanga',
    edit_profile: 'Hlela Iprofayile',
    save_profile: 'Gcina Iprofayile',
    greeting: 'Molo',
    track_my_application: 'Landelela Isicelo Sam',
    go_home: 'Buyela Ekhaya',
    processing_time: 'Ixesha lokuqhuba: Iintsuku eziyi-10–15 zomsebenzi',
    review_submit: 'Hlola & Thumela',
    proceed_to_payment: 'Qhubeka Nentlawulo',
    is_minor: 'Ngaba oku kungowomuntu omncinci (ngaphantsi kwe-16)?',
    yes: 'Ewe',
    no: 'Hayi',
    popi_compliance: 'Idatha yakho ikhuselwe phantsi kwe-POPI Act',
    sign_out: 'Phuma',
    security: 'Ukhuseleko',
    biometric_login: 'Ukungena Ngezimpawu Zomzimba',
    language_preference: 'Okuthandwayo Kolwimi',
    address: 'Idilesi',
    contact: 'Qhagamshelana',
    all: 'Konke',
    pending: 'Kulindile',
    completed: 'Kuqediwe',
    search_reference: 'Khangela ngenombolo yesalathiso...',
    status_timeline: 'Uhlelo Lwexesha Lemeko',
    new_app: 'Okutsha',
    filter: 'Hlela',
    application_detail: 'Iinkcukacha Zesicelo',
    city: 'Isixeko',
    province: 'Iphondo',
    country: 'Ilizwe',
    house_number: 'Inombolo Yendlu / Iyunithi',
    street: 'Igama Lomgaqo',
    suburb: 'Indawo',
    phone_secondary: 'Ifoni Yesibini (okukhethekileyo)',
    processing_payment: 'Icubungula intlawulo...',
    secure_payment: 'Iintlawulo zikhuselekile kwaye zikhipha imfihlo',
    sawubona: 'Molo',
    quick_actions: 'Izenzo Ezikhawulezayo',
    recent_applications: 'Izicelo Zamuva',
    digital_identity_hub: 'Iziko Lakho Lobuqu Bedijithali',
    south_africa: 'uMzantsi Afrika',
    view_all: 'Bona Konke',
    ha_verify_title: 'Ukuqinisekiswa Kobuqu',
    ha_verify_subtitle: 'Ngaphambi kokubhalisa, sidinga ukuqinisekisa ubuqu bakho ngokusebenzisa idatha ye-Home Affairs.',
    ha_what_you_need: 'Okufunekayo:',
    ha_need_id: 'Inombolo yakho ye-ID yoMzantsi Afrika enezinombolo eziyi-13',
    ha_need_name: 'Igama lakho lokuqala (njengoko likulo i-ID yakho)',
    ha_need_surname: 'Ifani yakho (njengoko ikulo i-ID yakho)',
    ha_need_face: 'Isithombe sakho sobuso sokubona ubuso',
    ha_demo_hint: 'Demo: I-ID 0000000000000 · Igama "Demo" · Ifani "User" · nayiphi na isithombe.',
    ha_start_verification: 'Qala Ukuqinisekisa',
    ha_enter_details: 'Faka Iinkcukacha Zakho',
    ha_enter_details_sub: 'Faka inombolo yakho ye-SA ID, igama lokuqala kunye nefani njengoko kubonakala kwimpepha-mvume yakho ye-ID.',
    ha_face_capture: 'Ukuqinisekiswa Kobuso',
    ha_face_capture_sub: 'Thatha isithombe sakho okanye layisha isithombe.',
    ha_tap_to_capture: 'Cofa ukuthatha isithombe',
    ha_use_camera: 'Thatha Isithombe',
    ha_from_gallery: 'Evela kwiGaleriya',
    ha_verify_now: 'Qinisekisa Ubuqu',
    ha_skip_photo: 'Qinisekisa Ngaphandle Kwesithombe',
    ha_verifying: 'Iyaqinisekisa Ubuqu...',
    ha_verifying_sub: 'Iyaxhumana nedatha ye-Home Affairs.',
    ha_verified: 'Ubuqu Buqinisekisiwe',
    ha_welcome: 'Wamkelekile,',
    ha_verified_sub: 'Ubuqu bakho buqinisekisiwe. Ngoku unokugqiba ukubhalisa kwakho.',
    ha_continue_register: 'Qhubeka Ukubhalisa',
    ha_not_verified: 'Ukuqinisekisa Kwehlulekile',
    ha_verify_identity: 'Qinisekisa Ubuqu ne-Home Affairs',
    ha_verify_required: 'Kufuneka ngaphambi kokubhalisa',
    ha_identity_verified: 'Ubuqu Buqinisekisiwe ✓',
    notif_submitted: 'Isicelo sithunyiwe ngempumelelo',
    notif_processing: 'Isicelo sakho siyacutshungulwa',
    notif_approved: 'Isicelo sakho samkelwe',
    notif_ready: 'Impepha-mvume yakho ilungele ukuqokelelwa',
    notif_payment_success: 'Intlawulo iphumelele',
    upload_photo: 'Layisha Isithombe',
    capture_photo: 'Thatha Isithombe',
    photo_uploaded: 'Isithombe silayishiwe',
    minor_biometrics: 'Ukuthwebula Izimpawu Zomzimba Zomntu Omncinci',
    minor_biometrics_sub: 'Thwebula izigxivizo zeminwe kunye nesithombe sobuso somntu omncinci.',
    capture_minor_face: 'Thwebula Isithombe Sobuso Somntu Omncinci',
    minor_face_captured: 'Isithombe sobuso sithwebulwe',
    status: 'Imeko',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY).then((stored) => {
      if (stored && ['en', 'af', 'zu', 'xh'].includes(stored)) {
        setLanguageState(stored as Language);
      }
    });
  }, []);

  const setLanguage = async (lang: Language) => {
    console.log('[Language] Setting language to:', lang);
    setLanguageState(lang);
    await AsyncStorage.setItem(STORAGE_KEY, lang);
  };

  const t = (key: string): string => {
    return translations[language][key] ?? translations['en'][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
